name: CI

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  pull_request: {}
  push:
    branches:
    - master
    - "!deps/**"
    tags:
    - v*
    paths-ignore:
    - docs/**
    - "*.md"

env:
  GO111MODULE: "on"

defaults:
  run:
    shell: bash

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Test multi-platform build
      run: |
        make test.build

  unit-test:
    if: contains(github.head_ref, 'deps/') == false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go:
        - 1.14.x
        - 1.15.x
        os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Ensure tidy gomod
      run: |
        go mod download -x
        go mod tidy
        if ! git diff --exit-code
        then
          echo "go mod not tidy"
          exit 1
        fi

    - name: Lint
      if: matrix.os == 'ubuntu-latest'
      run: |
        make lint.all

    - name: Unit Tests
      run: |
        make test.unit

    - name: Benchmark
      run: |
        make test.benchmark

    - name: Report Test Coverage
      uses: codecov/codecov-action@v1
      # with:
      #   token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #   fail_ci_if_error: true # optional (default = false)
